apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: NODE_ENV
            - name: IS_SWAGGER_ENABLED
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: IS_SWAGGER_ENABLED
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: DATABASE_URL
            - name: PRISMA_LOG_QUERIES
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: PRISMA_LOG_QUERIES
            - name: JWT_SECRET_AT
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: JWT_SECRET_AT
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: JWT_SECRET_RT
            - name: JWT_EXPIRATION_AT
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: JWT_EXPIRATION_AT
            - name: JWT_EXPIRATION_RT
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: JWT_EXPIRATION_RT
            - name: HTTP_ONLY
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: HTTP_ONLY
            - name: SECURE
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: SECURE
            - name: SAME_SITE
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: SAME_SITE
            - name: MAX_AGE
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: MAX_AGE
            - name: ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: snapflow-backend-production-config-secret
                  key: ALLOWED_ORIGINS